name: convert
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^5.0.0
  flutter_pdfview: ^1.0.4
  flutter_dropzone: ^4.2.0
 # Ensure this version supports Dart 3
  pdf: ^3.11.0            # Update to the latest compatible version
  printing: ^5.11.0
  image: ^4.1.0
  path_provider: ^2.0.12
  dio: ^4.0.6
  js: ^0.6.3     # For interfacing with JavaScript
  web: ^1.1.0    # For web support

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Update if necessary
